local remap = require("mrfixthis.keymap")
local nnoremap = remap.nnoremap

nnoremap("<leader>te", ":Telescope<CR>")
nnoremap("<C-p>", function() require("telescope.builtin").git_files() end)
nnoremap("<leader>th", function() require("telescope.builtin").help_tags() end)
nnoremap("<leader>gs", function() require("telescope.builtin").find_files() end)
nnoremap("<leader>bx", function() require("telescope.builtin").buffers() end)
nnoremap("<leader>gr", function() require("telescope.builtin").live_grep() end)
nnoremap("<leader>pw", function()
  require("telescope.builtin").grep_string({ search = vim.fn.expand("<cword>") })
end)
nnoremap("<leader>ps", function()
  require("telescope.builtin").grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<leader>do", function()
  require("mrfixthis.telescope.custom").search_nvm_dotfiles()
end)
nnoremap("<leader>dO", function()
  require("mrfixthis.telescope.custom").search_dotfiles()
end)
